### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by esseti** [Dashlane/homebrew-tap#8]
not an expert, this is the error, anything that i can do?
```
==> yarn install --frozen-lockfile
Last 15 lines from /Users/stefano/Library/Logs/Homebrew/dashlane-cli/02.yarn:
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ eslint is listed by your project with version 9.4.0, which doesn't satisfy what typescript-eslint (pfe5b0) and other dependencies request (^8.56.0).
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 528 packages were added to the project (+ 42.94 MiB).
➤ YN0000: └ Completed in 8s 590ms
➤ YN0000: ┌ Link step
➤ YN0007: │ better-sqlite3@npm:11.0.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0007: │ node-mac-auth@npm:1.1.0 must be built because it never has been before or the last one failed
➤ YN0009: │ node-mac-auth@npm:1.1.0 couldn't be built successfully (exit code 1, logs can be found here: /private/tmp/xfs-2f4e4707/build.log)
➤ YN0009: │ better-sqlite3@npm:11.0.0 couldn't be built successfully (exit code 1, logs can be found here: /private/tmp/xfs-2698ab40/build.log)
➤ YN0000: └ Completed in 6s 667ms
➤ YN0000: · Failed with errors in 15s 572ms
```

**Comment by Mikescops** [comment]
Hello,

Please share your system specification: OS, version...

**Comment by esseti** [comment]
MacOS: Version 15.0.1 (24A348)
PC: 13-inch, 2020, Four Thunderbolt 3 ports
Terminal: fish
Brew version: Homebrew 4.4.4
Homebrew/homebrew-core (git revision ee565b5b367; last commit 2024-11-04)
Homebrew/homebrew-cask (git revision 1a5b2168053; last commit 2024-11-04)

anything else that can help you out?

**Comment by neddonovan13** [comment]
I have the same issue on my cli install.

MacOS: 14.6.1
Macbook Pro M1 Max

Error is coming in running the dashlane CLI install according to these steps: https://cli.dashlane.com/install

**Comment by Mikescops** [comment]
@esseti @neddonovan13 hey folks, I have a hard time reproducing this error, if you can share logs that are mentioned here that would be super helpful `(exit code 1, logs can be found here: /private/tmp/xfs-2698ab40/build.log)`.

**Comment by neddonovan13** [comment]
Hey @Mikescops I hope your world is awesome!

Here's the terminal passthrough messaging:

```
==> Installing dashlane/tap/dashlane-cli
==> yarn set version 4.2.2
==> yarn install --frozen-lockfile
Last 15 lines from /Users/neddonovan/Library/Logs/Homebrew/dashlane-cli/02.yarn:
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ eslint is listed by your project with version 9.4.0, which doesn't satisfy what typescript-eslint (pfe5b0) and other dependencies request (^8.56.0).
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 528 packages were added to the project (+ 42.64 MiB).
➤ YN0000: └ Completed in 4s 789ms
➤ YN0000: ┌ Link step
➤ YN0007: │ better-sqlite3@npm:11.0.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0007: │ node-mac-auth@npm:1.1.0 must be built because it never has been before or the last one failed
➤ YN0009: │ node-mac-auth@npm:1.1.0 couldn't be built successfully (exit code 1, logs can be found here: /private/tmp/xfs-257c9cde/build.log)
➤ YN0000: └ Completed in 3s 780ms
➤ YN0000: · Failed with errors in 8s 705ms

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/dashlane/homebrew-tap/issues
```
[build.log](https://github.com/user-attachments/files/17717836/build.log)

Let me know if this works!

**Comment by Mikescops** [comment]
Hey @neddonovan13, all good for me, I hope same for you it's been a while 👍 

Can you try the following one by one (testing install dashlane-cli after each):

1- Installing xcode tools
```
xcode-select --install
```

2- Installing libc++ module
```
brew install llvm
```

Thanks!

**Comment by Mikescops** [comment]
@neddonovan13  Can you share the build.log to see if it has changed?

**Comment by neddonovan13** [comment]
Hey @Mikescops here's the most recent build.log.

If it's not possible it's not possible but I'm for *sure* at a loss as to why!

[build.log](https://github.com/user-attachments/files/17756206/build.log)

**Comment by esseti** [comment]
Sorry for not repling. in the end i installed the pacakge manually without brew.

**Comment by neddonovan13** [comment]
@Mikescops I actually solved it last night! I had systems permissioning left over from an old work remote connection that was blocking certain parts of processing. I got that workflow completely uninstalled and it connected just fine!

**Comment by Mikescops** [comment]
Ok thanks both, I'll close the issue, feel free to reopen if anything new comes in.
